import { createClient } from "./supabase/client";

// For backward compatibility - use the new client structure
export const supabase = createClient();

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          first_name: string | null;
          last_name: string | null;
          phone: string | null;
          title: string | null;
          bio: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          zip_code: string | null;
          license_number: string | null;
          years_experience: number | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          title?: string | null;
          bio?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          license_number?: string | null;
          years_experience?: number | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          title?: string | null;
          bio?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          license_number?: string | null;
          years_experience?: number | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      clients: {
        Row: {
          id: string;
          dietitian_id: string;
          name: string;
          email: string;
          phone: string | null;
          address: string | null;
          age: number | null;
          height: string | null;
          current_weight: number | null;
          goal_weight: number | null;
          goal: string;
          plan_type: string;
          status: string;
          tags: string[];
          notes: string | null;
          emergency_contact: string | null;
          join_date: string;
          last_session: string | null;
          next_appointment: string | null;
          progress_percentage: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          dietitian_id: string;
          name: string;
          email: string;
          phone?: string | null;
          address?: string | null;
          age?: number | null;
          height?: string | null;
          current_weight?: number | null;
          goal_weight?: number | null;
          goal: string;
          plan_type?: string;
          status?: string;
          tags?: string[];
          notes?: string | null;
          emergency_contact?: string | null;
          join_date?: string;
          last_session?: string | null;
          next_appointment?: string | null;
          progress_percentage?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          dietitian_id?: string;
          name?: string;
          email?: string;
          phone?: string | null;
          address?: string | null;
          age?: number | null;
          height?: string | null;
          current_weight?: number | null;
          goal_weight?: number | null;
          goal?: string;
          plan_type?: string;
          status?: string;
          tags?: string[];
          notes?: string | null;
          emergency_contact?: string | null;
          join_date?: string;
          last_session?: string | null;
          next_appointment?: string | null;
          progress_percentage?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      client_accounts: {
        Row: {
          id: string;
          client_id: string;
          email: string;
          password_hash: string;
          is_active: boolean;
          last_login: string | null;
          password_reset_token: string | null;
          password_reset_expires: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          email: string;
          password_hash: string;
          is_active?: boolean;
          last_login?: string | null;
          password_reset_token?: string | null;
          password_reset_expires?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          email?: string;
          password_hash?: string;
          is_active?: boolean;
          last_login?: string | null;
          password_reset_token?: string | null;
          password_reset_expires?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      meal_plans: {
        Row: {
          id: string;
          client_id: string;
          dietitian_id: string;
          name: string;
          description: string | null;
          plan_content: any;
          calories_range: string | null;
          duration_days: number;
          status: string;
          template_id: string | null;
          generation_method: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          dietitian_id: string;
          name: string;
          description?: string | null;
          plan_content: any;
          calories_range?: string | null;
          duration_days?: number;
          status?: string;
          template_id?: string | null;
          generation_method?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          dietitian_id?: string;
          name?: string;
          description?: string | null;
          plan_content?: any;
          calories_range?: string | null;
          duration_days?: number;
          status?: string;
          template_id?: string | null;
          generation_method?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          client_id: string;
          dietitian_id: string;
          invoice_number: string;
          service_description: string;
          amount: number;
          status: string;
          issue_date: string;
          due_date: string;
          payment_date: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          dietitian_id: string;
          invoice_number: string;
          service_description: string;
          amount: number;
          status?: string;
          issue_date?: string;
          due_date: string;
          payment_date?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          dietitian_id?: string;
          invoice_number?: string;
          service_description?: string;
          amount?: number;
          status?: string;
          issue_date?: string;
          due_date?: string;
          payment_date?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      reminders: {
        Row: {
          id: string;
          client_id: string;
          dietitian_id: string;
          type: string;
          title: string;
          message: string;
          scheduled_date: string;
          is_recurring: boolean;
          frequency: string | null;
          channels: string[];
          status: string;
          sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          dietitian_id: string;
          type: string;
          title: string;
          message: string;
          scheduled_date: string;
          is_recurring?: boolean;
          frequency?: string | null;
          channels?: string[];
          status?: string;
          sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          dietitian_id?: string;
          type?: string;
          title?: string;
          message?: string;
          scheduled_date?: string;
          is_recurring?: boolean;
          frequency?: string | null;
          channels?: string[];
          status?: string;
          sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      recipe_templates: {
        Row: {
          id: string;
          dietitian_id: string;
          name: string;
          description: string | null;
          category: string;
          meal_type: string;
          cuisine_type: string;
          health_benefits: string[] | null;
          dietary_type: string[];
          preparation_time: number | null;
          cooking_time: number | null;
          servings: number;
          calories_per_serving: number | null;
          macros: any | null;
          ingredients: any;
          instructions: any;
          tags: string[];
          difficulty: string;
          rating: number | null;
          usage_count: number;
          is_favorite: boolean;
          is_public: boolean;
          source: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          dietitian_id: string;
          name: string;
          description?: string | null;
          category: string;
          meal_type?: string;
          cuisine_type?: string;
          health_benefits?: string[] | null;
          dietary_type?: string[];
          preparation_time?: number | null;
          cooking_time?: number | null;
          servings?: number;
          calories_per_serving?: number | null;
          macros?: any | null;
          ingredients: any;
          instructions: any;
          tags?: string[];
          difficulty?: string;
          rating?: number | null;
          usage_count?: number;
          is_favorite?: boolean;
          is_public?: boolean;
          source?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          dietitian_id?: string;
          name?: string;
          description?: string | null;
          category?: string;
          meal_type?: string;
          cuisine_type?: string;
          health_benefits?: string[] | null;
          dietary_type?: string[];
          preparation_time?: number | null;
          cooking_time?: number | null;
          servings?: number;
          calories_per_serving?: number | null;
          macros?: any | null;
          ingredients?: any;
          instructions?: any;
          tags?: string[];
          difficulty?: string;
          rating?: number | null;
          usage_count?: number;
          is_favorite?: boolean;
          is_public?: boolean;
          source?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      meal_plan_templates: {
        Row: {
          id: string;
          dietitian_id: string;
          name: string;
          description: string | null;
          category: string;
          client_type: string;
          health_condition: string | null;
          goal_type: string;
          duration_days: number;
          target_calories: string | null;
          target_macros: any | null;
          meal_structure: any;
          tags: string[];
          difficulty: string;
          rating: number | null;
          usage_count: number;
          is_favorite: boolean;
          is_public: boolean;
          last_used_at: string | null;
          created_at: string;
          updated_at: string;
          estimated_prep_time_total: number | null;
          shopping_list_template: any | null;
          allergen_info: string[] | null;
          cuisine_type: string | null;
          budget_level: string | null;
          season: string | null;
          equipment_needed: string[] | null;
        };
        Insert: {
          id?: string;
          dietitian_id: string;
          name: string;
          description?: string | null;
          category: string;
          client_type?: string;
          health_condition?: string | null;
          goal_type?: string;
          duration_days?: number;
          target_calories?: string | null;
          target_macros?: any | null;
          meal_structure: any;
          tags?: string[];
          difficulty?: string;
          rating?: number | null;
          usage_count?: number;
          is_favorite?: boolean;
          is_public?: boolean;
          last_used_at?: string | null;
          created_at?: string;
          updated_at?: string;
          estimated_prep_time_total?: number | null;
          shopping_list_template?: any | null;
          allergen_info?: string[] | null;
          cuisine_type?: string | null;
          budget_level?: string | null;
          season?: string | null;
          equipment_needed?: string[] | null;
        };
        Update: {
          id?: string;
          dietitian_id?: string;
          name?: string;
          description?: string | null;
          category?: string;
          client_type?: string;
          health_condition?: string | null;
          goal_type?: string;
          duration_days?: number;
          target_calories?: string | null;
          target_macros?: any | null;
          meal_structure?: any;
          tags?: string[];
          difficulty?: string;
          rating?: number | null;
          usage_count?: number;
          is_favorite?: boolean;
          is_public?: boolean;
          last_used_at?: string | null;
          created_at?: string;
          updated_at?: string;
          estimated_prep_time_total?: number | null;
          shopping_list_template?: any | null;
          allergen_info?: string[] | null;
          cuisine_type?: string | null;
          budget_level?: string | null;
          season?: string | null;
          equipment_needed?: string[] | null;
        };
      };
      appointments: {
        Row: {
          id: string;
          dietitian_id: string;
          client_id: string;
          title: string;
          description: string | null;
          appointment_date: string;
          appointment_time: string;
          duration_minutes: number;
          type: string;
          status: string;
          location: string | null;
          is_virtual: boolean;
          meeting_link: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          dietitian_id: string;
          client_id: string;
          title: string;
          description?: string | null;
          appointment_date: string;
          appointment_time: string;
          duration_minutes?: number;
          type?: string;
          status?: string;
          location?: string | null;
          is_virtual?: boolean;
          meeting_link?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          dietitian_id?: string;
          client_id?: string;
          title?: string;
          description?: string | null;
          appointment_date?: string;
          appointment_time?: string;
          duration_minutes?: number;
          type?: string;
          status?: string;
          location?: string | null;
          is_virtual?: boolean;
          meeting_link?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          client_id: string;
          dietitian_id: string;
          subject: string | null;
          status: string;
          priority: string;
          last_message_at: string;
          unread_count: number;
          is_starred: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          dietitian_id: string;
          subject?: string | null;
          status?: string;
          priority?: string;
          last_message_at?: string;
          unread_count?: number;
          is_starred?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          dietitian_id?: string;
          subject?: string | null;
          status?: string;
          priority?: string;
          last_message_at?: string;
          unread_count?: number;
          is_starred?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      documents: {
        Row: {
          id: string;
          client_id: string;
          dietitian_id: string;
          name: string;
          file_path: string;
          file_size: number | null;
          mime_type: string | null;
          category: string;
          description: string | null;
          upload_date: string;
          is_visible_to_client: boolean;
          metadata: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          dietitian_id: string;
          name: string;
          file_path: string;
          file_size?: number | null;
          mime_type?: string | null;
          category?: string;
          description?: string | null;
          upload_date?: string;
          is_visible_to_client?: boolean;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          dietitian_id?: string;
          name?: string;
          file_path?: string;
          file_size?: number | null;
          mime_type?: string | null;
          category?: string;
          description?: string | null;
          upload_date?: string;
          is_visible_to_client?: boolean;
          metadata?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          client_id: string;
          dietitian_id: string;
          conversation_id: string | null;
          sender_type: string;
          message: string;
          content: string | null;
          message_type: string;
          attachment_url: string | null;
          attachment_name: string | null;
          is_read: boolean;
          read_at: string | null;
          metadata: any;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          dietitian_id: string;
          conversation_id?: string | null;
          sender_type: string;
          message: string;
          content?: string | null;
          message_type?: string;
          attachment_url?: string | null;
          attachment_name?: string | null;
          is_read?: boolean;
          read_at?: string | null;
          metadata?: any;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          dietitian_id?: string;
          conversation_id?: string | null;
          sender_type?: string;
          message?: string;
          content?: string | null;
          message_type?: string;
          attachment_url?: string | null;
          attachment_name?: string | null;
          is_read?: boolean;
          read_at?: string | null;
          metadata?: any;
          created_at?: string;
        };
      };
      recipes: {
        Row: {
          id: string;
          dietitian_id: string;
          name: string;
          description: string | null;
          category: string;
          prep_time: number | null;
          cook_time: number | null;
          servings: number;
          difficulty: string;
          calories_per_serving: number | null;
          protein_per_serving: number | null;
          carbs_per_serving: number | null;
          fat_per_serving: number | null;
          fiber_per_serving: number | null;
          image_url: string | null;
          instructions: string[];
          tags: string[];
          is_favorite: boolean;
          usage_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          dietitian_id: string;
          name: string;
          description?: string | null;
          category?: string;
          prep_time?: number | null;
          cook_time?: number | null;
          servings?: number;
          difficulty?: string;
          calories_per_serving?: number | null;
          protein_per_serving?: number | null;
          carbs_per_serving?: number | null;
          fat_per_serving?: number | null;
          fiber_per_serving?: number | null;
          image_url?: string | null;
          instructions?: string[];
          tags?: string[];
          is_favorite?: boolean;
          usage_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          dietitian_id?: string;
          name?: string;
          description?: string | null;
          category?: string;
          prep_time?: number | null;
          cook_time?: number | null;
          servings?: number;
          difficulty?: string;
          calories_per_serving?: number | null;
          protein_per_serving?: number | null;
          carbs_per_serving?: number | null;
          fat_per_serving?: number | null;
          fiber_per_serving?: number | null;
          image_url?: string | null;
          instructions?: string[];
          tags?: string[];
          is_favorite?: boolean;
          usage_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      recipe_ingredients: {
        Row: {
          id: string;
          recipe_id: string;
          name: string;
          quantity: number | null;
          unit: string | null;
          notes: string | null;
          order_index: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          name: string;
          quantity?: number | null;
          unit?: string | null;
          notes?: string | null;
          order_index?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          name?: string;
          quantity?: number | null;
          unit?: string | null;
          notes?: string | null;
          order_index?: number;
          created_at?: string;
        };
      };
      meal_plan_recipes: {
        Row: {
          id: string;
          meal_plan_id: string;
          recipe_id: string;
          day_number: number;
          meal_type: string;
          servings_used: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          meal_plan_id: string;
          recipe_id: string;
          day_number: number;
          meal_type: string;
          servings_used?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          meal_plan_id?: string;
          recipe_id?: string;
          day_number?: number;
          meal_type?: string;
          servings_used?: number;
          created_at?: string;
        };
      };
      dietitians: {
        Row: {
          id: string;
          auth_user_id: string;
          email: string;
          first_name: string | null;
          last_name: string | null;
          phone: string | null;
          title: string | null;
          bio: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          zip_code: string | null;
          license_number: string | null;
          years_experience: number | null;
          avatar_url: string | null;
          stripe_customer_id: string | null;
          subscription_status: string;
          subscription_id: string | null;
          subscription_plan: string;
          subscription_started_at: string | null;
          subscription_ends_at: string | null;
          trial_ends_at: string | null;
          subscription_current_period_end: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          auth_user_id: string;
          email: string;
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          title?: string | null;
          bio?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          license_number?: string | null;
          years_experience?: number | null;
          avatar_url?: string | null;
          stripe_customer_id?: string | null;
          subscription_status?: string;
          subscription_id?: string | null;
          subscription_plan?: string;
          subscription_started_at?: string | null;
          subscription_ends_at?: string | null;
          trial_ends_at?: string | null;
          subscription_current_period_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          auth_user_id?: string;
          email?: string;
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          title?: string | null;
          bio?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          zip_code?: string | null;
          license_number?: string | null;
          years_experience?: number | null;
          avatar_url?: string | null;
          stripe_customer_id?: string | null;
          subscription_status?: string;
          subscription_id?: string | null;
          subscription_plan?: string;
          subscription_started_at?: string | null;
          subscription_ends_at?: string | null;
          trial_ends_at?: string | null;
          subscription_current_period_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      subscription_plans: {
        Row: {
          id: string;
          name: string;
          display_name: string;
          stripe_price_id: string;
          price_monthly: number;
          currency: string;
          features: any;
          max_clients: number | null;
          max_meal_plans: number | null;
          ai_generations_per_month: number | null;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          display_name: string;
          stripe_price_id: string;
          price_monthly: number;
          currency?: string;
          features?: any;
          max_clients?: number | null;
          max_meal_plans?: number | null;
          ai_generations_per_month?: number | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          display_name?: string;
          stripe_price_id?: string;
          price_monthly?: number;
          currency?: string;
          features?: any;
          max_clients?: number | null;
          max_meal_plans?: number | null;
          ai_generations_per_month?: number | null;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      subscription_events: {
        Row: {
          id: string;
          dietitian_id: string;
          event_type: string;
          stripe_event_id: string | null;
          stripe_subscription_id: string | null;
          previous_status: string | null;
          new_status: string | null;
          previous_plan: string | null;
          new_plan: string | null;
          metadata: any | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          dietitian_id: string;
          event_type: string;
          stripe_event_id?: string | null;
          stripe_subscription_id?: string | null;
          previous_status?: string | null;
          new_status?: string | null;
          previous_plan?: string | null;
          new_plan?: string | null;
          metadata?: any | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          dietitian_id?: string;
          event_type?: string;
          stripe_event_id?: string | null;
          stripe_subscription_id?: string | null;
          previous_status?: string | null;
          new_status?: string | null;
          previous_plan?: string | null;
          new_plan?: string | null;
          metadata?: any | null;
          created_at?: string;
        };
      };
    };
  };
}

export type Client = Database["public"]["Tables"]["clients"]["Row"];
export type ClientAccount =
  Database["public"]["Tables"]["client_accounts"]["Row"];
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type MealPlan = Database["public"]["Tables"]["meal_plans"]["Row"];
export type Invoice = Database["public"]["Tables"]["invoices"]["Row"];
export type Reminder = Database["public"]["Tables"]["reminders"]["Row"];
export type RecipeTemplate =
  Database["public"]["Tables"]["recipe_templates"]["Row"];
export type MealPlanTemplate =
  Database["public"]["Tables"]["meal_plan_templates"]["Row"];
export type Appointment = Database["public"]["Tables"]["appointments"]["Row"];
export type Conversation = Database["public"]["Tables"]["conversations"]["Row"];
export type Message = Database["public"]["Tables"]["messages"]["Row"];
export type Recipe = Database["public"]["Tables"]["recipes"]["Row"];
export type RecipeIngredient = Database["public"]["Tables"]["recipe_ingredients"]["Row"];
export type MealPlanRecipe = Database["public"]["Tables"]["meal_plan_recipes"]["Row"];
export type Dietitian = Database["public"]["Tables"]["dietitians"]["Row"];
export type SubscriptionPlan = Database["public"]["Tables"]["subscription_plans"]["Row"];
export type SubscriptionEvent = Database["public"]["Tables"]["subscription_events"]["Row"];

export interface Document {
  id: string;
  client_id: string;
  dietitian_id: string;
  name: string;
  file_path: string;
  file_size: number | null;
  mime_type: string | null;
  category: string;
  description: string | null;
  upload_date: string;
  is_visible_to_client: boolean;
  metadata: any;
  created_at: string;
  updated_at: string;
}

export type SubscriptionStatus = 'trialing' | 'active' | 'past_due' | 'canceled' | 'incomplete' | 'incomplete_expired';
export type SubscriptionPlanName = 'free' | 'starter';
